global:
  apiVersionOverrides:
  certmanager: "" # cert-manager.io/v1
  ingress: "" # networking.k8s.io/v1beta1

controller:
  serviceAccount:
    create: true
    name: argocd-controller
    ## Annotations applied to created service account
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/role-name
    ## Automount API credentials for the Service Account
    automountServiceAccountToken: true

dex:
  serviceAccount:
    create: true
    name: argocd-dex-server
    ## Annotations applied to created service account
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/role-name
    ## Automount API credentials for the Service Account
    automountServiceAccountToken: true

server:
  extraArgs:
    --insecure
  serviceAccount:
    create: true
    name: argocd-server
    ## Annotations applied to created service account
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/role-name
    ## Automount API credentials for the Service Account
    automountServiceAccountToken: true
  service:
    annotations: {}
    labels: {}
    type: NodePort
    #LoadBalancer
    ## For node port default ports
    nodePortHttp: 30080
    nodePortHttps: 30443
    servicePortHttp: 80
    servicePortHttps: 443
    servicePortHttpName: http
    servicePortHttpsName: https
    namedTargetPort: true
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalIPs: []
    externalTrafficPolicy: ""
    sessionAffinity: ""

  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: alb
    labels: {}
    ingressClassName: "argocd"

    ## Argo Ingress.
    ## Hostnames must be provided if Ingress is enabled.
    ## Secrets must be manually created in the namespace
    ##
    hosts:
      - argocd.reines-test.link
      # - argocd.example.com
    paths:
      - /
    pathType: Prefix
    extraPaths:
      []
      # - path: /*
      #   backend:
      #     serviceName: ssl-redirect
      #     servicePort: use-annotation
      ## for Kubernetes >=1.19 (when "networking.k8s.io/v1" is used)
      # - path: /*
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: ssl-redirect
      #       port:
      #         name: use-annotation
    tls:
      - secretName: tls-certmanager
        hosts:
          - argocd.reines-test.link
    https: true
  # dedicated ingress for gRPC as documented at
  # https://argoproj.github.io/argo-cd/operator-manual/ingress/

    config:
      accounts.viewer: apiKey, login
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      url: https://argocd.example.com
      # Argo CD instance label key
      application.instanceLabelKey: argocd.argoproj.io/instance
      # repositories: |
      #   - url: git@github.com:group/repo.git
      #     sshPrivateKeySecret:
      #       name: secret-name
      #       key: sshPrivateKey
      #   - type: helm
      #     url: https://charts.helm.sh/stable
      #     name: stable
      #   - type: helm
      #     url: https://argoproj.github.io/argo-helm
      #     name: argo
      # oidc.config: |
      #   name: AzureAD
      #   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
      #   clientID: CLIENT_ID
      #   clientSecret: $oidc.azuread.clientSecret
      #   requestedIDTokenClaims:
      #     groups:
      #       essential: true
      #   requestedScopes:
      #     - openid
      #     - profile
      #     - email
    rbacConfig:
      policy.default: role:'' #(readonly?‹œ defaultë¡? ëª¨ë‘ readonly)
      policy.scv: | #(?œ ??? ë°? ê·¸ë£¹ ê¶Œí•œ ?„¤? •) 
        p, role:viewer, applications, get, */*, allow
        p, role:viewer, accounts, get, *, allow
        p, role:viewer, certificates, get, *, allow
        p, role:viewer, clusters, get, *, allow
        p, role:viewer, repositories, get, *, allow
        p, role:viewer, projects, get, *, allow
        p, role:viewer, gpgkeys, get, *, allow
        g, viewer, role:viewer

  ingressGrpc:
    enabled: false
    isAWSALB: false
    annotations: {}
    labels: {}
    ingressClassName: ""

    ## Service Type if isAWSALB is set to true
    ## Can be of type NodePort or ClusterIP depending on which mode you are
    ## are running. Instance mode needs type NodePort, IP mode needs type
    ## ClusterIP
    ## Ref: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/how-it-works/#ingress-traffic
    ##
    awsALB:
      serviceType: NodePort
    #LoadBalancer

    ## Argo Ingress.
    ## Hostnames must be provided if Ingress is enabled.
    ## Secrets must be manually created in the namespace
    ##
    hosts:
      []
      # - argocd.example.com
    paths:
      - /
    pathType: Prefix
    extraPaths:
      []
      # - path: /*
      #   backend:
      #     serviceName: ssl-redirect
      #     servicePort: use-annotation
      ## for Kubernetes >=1.19 (when "networking.k8s.io/v1" is used)
      # - path: /*
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: ssl-redirect
      #       port:
      #         name: use-annotation
    tls:
      []
      # - secretName: argocd-tls-certificate
      #   hosts:
      #     - argocd.example.com
    https: false
    